name: Node.js CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [20.x]

    steps:
    - uses: actions/checkout@v4
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v4
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'

    - run: npm ci

    # Start the server in the background and wait for it to be ready
    - name: Start server in the background
      run: |
        npm start &  # Run the server in the background
        sleep 10     # Wait for a few seconds to give the server time to start

    # Now you can add your tests or any subsequent steps
    - name: Run tests
      run: npm test
